#!/bin/bash

# This is a thin wrapper around solari-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using solari-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_SOLARID

# Grab the value of $REAL_SOLARICLI which may be solari-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_SOLARICLI}" "$@" | sed 's/\r//'
